# Dockerfile1

ARG  BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

# accept dynamic argument
ARG APP_NAME
ENV APP_VERSION=${APP_VERSION}

# SET ENVIRONMENT VARIABLES
ENV ENVIRONMENT=production

COPY . .

CMD [ "python", 'app.py']