# Dockerfile2 

ARG BASE_IMAGE
FROM ${BASE_IMAGE}

WORKDIR /app

# accept dynamic argument
ARG APP_NAME
ENV APP_NAME=${APP_NAME}

# Set environmental variables
ENV  ENVIRONMENT=development

COPY . .

CMD [ "node", "app.js" ]
